CREATE TABLE bonus_card
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    card_number VARCHAR(16) NOT NULL,
    balance     NUMERIC(19, 2)  NOT NULL DEFAULT 0.00,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT  pk_bonus_card   PRIMARY KEY (id),
    CONSTRAINT  uk_bonus_card_card_number   UNIQUE (card_number)
);

CREATE TABLE bonus_operation
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    card_id         BIGINT NOT NULL,
    operation_type  VARCHAR(20) NOT NULL,
    amount          NUMERIC(19, 2) NOT NULL,
    balance_change  NUMERIC(19, 2) NOT NULL,
    balance_after   NUMERIC(19, 2) NOT NULL,
    reversal_of_operation_id    BIGINT,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT pk_bonus_operation PRIMARY KEY (id),

    CONSTRAINT uk_bonus_operation_reversal_of
        UNIQUE (reversal_of_operation_id),

    CONSTRAINT fk_bonus_operation_card
        FOREIGN KEY (card_id)
        REFERENCES bonus_card (id),

    CONSTRAINT fk_bonus_operation_reversal_of
        FOREIGN KEY (reversal_of_operation_id)
        REFERENCES bonus_operation (id)
);