CREATE TABLE app_user
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username        VARCHAR(100) NOT NULL,
    password_hash   VARCHAR(255) NOT NULL,
    enabled         BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_app_user PRIMARY KEY (id),
    CONSTRAINT uk_app_user_username UNIQUE (username)
);

CREATE TABLE app_role
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name    VARCHAR(50) NOT NULL,

    CONSTRAINT pk_app_role PRIMARY KEY (id),
    CONSTRAINT uk_app_role_name UNIQUE (name)
);

CREATE TABLE user_role
(
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,

    CONSTRAINT pk_user_role PRIMARY KEY (user_id, role_id),

    CONSTRAINT fk_user_role_user
        FOREIGN KEY (user_id)
        REFERENCES app_user (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_user_role_role
        FOREIGN KEY (role_id)
        REFERENCES app_role (id)
        ON DELETE CASCADE
);

INSERT INTO app_role (name)
SELECT 'READ'
WHERE NOT EXISTS (
    SELECT 1
    FROM app_role
    WHERE name = 'READ'
);

INSERT INTO app_role (name)
SELECT 'WRITE'
WHERE NOT EXISTS (
    SELECT 1
    FROM app_role
    WHERE name = 'WRITE'
);